### PR TITLE
Added capping of created collection

### PR DESCRIPTION
**Pull request by tobiasb**
This adds the possibility to have the appender initially create a capped collection to prevent the collection size from getting out of hand.

### CODE REVIEW

**Comment by tobiasb** [comment]
Any ideas what I could do to increase the chance of having this merged?

**Comment by jsk** [comment]
@gimmi can you please check this PR ?
@tobiasb is it possible to add tests for this feature ?

**Comment by tobiasb** [comment]
@jsk will do. Will also add documentation.

**Comment by tobiasb** [comment]
Added tests and documentation. Let me know what you think @gimmi and @jsk .

**Comment by jsk** [comment]
@emadb can you check this ?

**Comment by emadb** [comment]
Hi @tobiasb 
Thanks for the PR. We are sorry but we upgrade the package to the new drivers (2.0). May I ask you to update your PR to macth the new version of the mongo drivers?

**Comment by emadb** [comment]
Hi @tobiasb 
In the last weeks we upgrade the project to the new Mongodb drivers (2.0) and your PR needs a check. 
I resolved the conflicts and I created a branch (tobiasb-capping-created-collections) that you can check. If you have time to review the merge that I've done it would be great.

Thx

**Comment by tobiasb** [comment]
@emadb
PR updated. I rebased my fork and resolved the merge conflicts. Please have a look.

/cc @jsk

**Comment by emadb** [comment]
Thx!!!

**Pull request merged**
